---
name: website-stack
description: "Stack for my super website"
components:
  db:
    stack: ../mysql-stack/
  db2:
    stack: ../mysql-embed-stack/
  wp:
    stack: ../wordpress-stack/
  wp2:
    stack: ../wordpress-stack/
relations:
  - requirer: wp:db
    provider: db:db
  - requirer: wp2:db
    provider: db2:db
