# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
---
name: website-stack
description: "Stack for my super website"
components:
  db:
    stack: ../mysql-stack/
  wp:
    stack: ../wordpress-stack/
relations:
  - requirer: wp:db
    provider: db:db
