# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
---
name: mysql-stack
description: "Stack for my MySQL Database"
components:
  mysql:
    charm: charmed-osm-mariadb-k8s
    num_units: 1
provides:
  db:
    forward: mysql:mysql
