# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
---
name: website
description: "Stack with hello kubecon"
components:
  site:
    charm: hello-kubecon
requires:
  site-ingress:
    forward: site:ingress
