# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
---
name: website-lma
description: "Website stack with LMA"
components:
  site:
    charm: hello-kubecon
  ingress:
    charm: nginx-ingress-integrator
    units: 1
  lma:
    stack: lma
relations:
  - provider: ingress:ingress
    requirer: website:site-ingress
