# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
---
name: website-lma
description: "Website stack with LMA"
components:
  website:
    stack: website
  lma:
    stack: lma
  ingress:
    charm: nginx-ingress-integrator
    units: 1
relations:
- provider: ingress:ingress
  requirer: website:site-ingress